---
abstract: "MaxMind's plugin bundle"
author:
  - 'Dave Rolsky <drolsky@maxmind.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.88'
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: v5.10.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.030, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-MAXMIND
no_index:
  package:
    - Dist::Zilla::Plugin::MAXMIND::Contributors
    - Dist::Zilla::Plugin::MAXMIND::License
provides:
  Dist::Zilla::PluginBundle::MAXMIND:
    file: lib/Dist/Zilla/PluginBundle/MAXMIND.pm
    version: '0.05'
requires:
  Dist::Zilla: '0'
  Dist::Zilla::File::InMemory: '0'
  Dist::Zilla::Plugin::Authority: '0'
  Dist::Zilla::Plugin::AutoPrereqs: '0'
  Dist::Zilla::Plugin::CPANFile: '0'
  Dist::Zilla::Plugin::CheckPrereqsIndexed: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::Git::Check: '0'
  Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts: '0'
  Dist::Zilla::Plugin::Git::Commit: '0'
  Dist::Zilla::Plugin::Git::Contributors: '0'
  Dist::Zilla::Plugin::Git::Describe: '0'
  Dist::Zilla::Plugin::Git::Push: '0'
  Dist::Zilla::Plugin::Git::Tag: '0'
  Dist::Zilla::Plugin::GitHub::Meta: '0'
  Dist::Zilla::Plugin::GitHub::Update: '0'
  Dist::Zilla::Plugin::InstallGuide: '0'
  Dist::Zilla::Plugin::Meta::Contributors: '0'
  Dist::Zilla::Plugin::MetaConfig: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaProvides::Package: '0'
  Dist::Zilla::Plugin::MetaResources: '0'
  Dist::Zilla::Plugin::MinimumPerl: '0'
  Dist::Zilla::Plugin::MojibakeTests: '0'
  Dist::Zilla::Plugin::NextRelease: '0'
  Dist::Zilla::Plugin::PkgVersion: '0'
  Dist::Zilla::Plugin::PodSyntaxTests: '0'
  Dist::Zilla::Plugin::PromptIfStale: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::SurgicalPodWeaver: '0'
  Dist::Zilla::Plugin::Test::CPAN::Changes: '0'
  Dist::Zilla::Plugin::Test::Compile: '0'
  Dist::Zilla::Plugin::Test::EOL: '0.14'
  Dist::Zilla::Plugin::Test::NoTabs: '0'
  Dist::Zilla::Plugin::Test::Pod::Coverage::Configurable: '0'
  Dist::Zilla::Plugin::Test::PodSpelling: '0'
  Dist::Zilla::Plugin::Test::Portability: '0'
  Dist::Zilla::Plugin::Test::ReportPrereqs: '0'
  Dist::Zilla::Plugin::Test::Synopsis: '0'
  Dist::Zilla::Role::AfterBuild: '0'
  Dist::Zilla::Role::BeforeBuild: '0'
  Dist::Zilla::Role::LicenseProvider: '0'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  Moose: '0'
  Pod::Weaver::Section::Contributors: '0'
  Software::License::Perl_5: '0'
  autodie: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/maxmind/Dist-Zilla-PluginBundle-MAXMIND.git
version: '0.05'
x_Dist_Zilla:
  perl:
    version: '5.016003'
  plugins:
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@MAXMIND/MakeMaker'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@MAXMIND/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@MAXMIND/AutoPrereqs'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@MAXMIND/CopyFilesFromBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - README.md
            - cpanfile
            - Makefile.PL
            - LICENSE
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
      name: '@MAXMIND/GatherDir'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@MAXMIND/GitHub::Meta'
      version: '0.39'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@MAXMIND/GitHub::Update'
      version: '0.39'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@MAXMIND/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.030'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@MAXMIND/MetaProvides::Package'
      version: '2.002000'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@MAXMIND/NextRelease'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@MAXMIND/Test::PodSpelling'
      version: '2.006008'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@MAXMIND/Test::ReportPrereqs'
      version: '0.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@MAXMIND/TestMoreDoneTesting'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: '1'
          check_all_prereqs: '1'
          modules: []
          phase: release
          skip:
            - Dist::Zilla::Plugin::MAXMIND::Contributors
            - Dist::Zilla::Plugin::MAXMIND::License
      name: '@MAXMIND/stale modules, release'
      version: '0.033'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@MAXMIND/ReadmeMarkdownInBuild'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@MAXMIND/ReadmeMarkdownInRoot'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@MAXMIND/UploadToCPAN'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@MAXMIND/PruneCruft'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@MAXMIND/ManifestSkip'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@MAXMIND/MetaYAML'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::License
      name: '@MAXMIND/License'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@MAXMIND/ExtraTests'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@MAXMIND/ExecDir'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@MAXMIND/ShareDir'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@MAXMIND/Manifest'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@MAXMIND/TestRelease'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@MAXMIND/ConfirmRelease'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@MAXMIND/CheckPrereqsIndexed'
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@MAXMIND/CPANFile'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::CheckFor::CorrectBranch'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::CheckFor::MergeConflicts'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@MAXMIND/Git::Describe'
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          include_authors: '0'
          include_releaser: '1'
          order_by: name
          paths: []
      name: '@MAXMIND/Git::Contributors'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@MAXMIND/InstallGuide'
      version: '1.200005'
    -
      class: Dist::Zilla::Plugin::MAXMIND::Contributors
      name: '@MAXMIND/MAXMIND::Contributors'
      version: ~
    -
      class: Dist::Zilla::Plugin::MAXMIND::License
      name: '@MAXMIND/MAXMIND::License'
      version: ~
    -
      class: Dist::Zilla::Plugin::Meta::Contributors
      name: '@MAXMIND/Meta::Contributors'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@MAXMIND/MetaConfig'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@MAXMIND/MetaJSON'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@MAXMIND/MinimumPerl'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@MAXMIND/PkgVersion'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::SurgicalPodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.008'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.008'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.008'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.008'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.008'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.008'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.008'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.008'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.008'
            -
              class: Pod::Weaver::Section::Contributors
              name: Contributors
              version: '0.009'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.008'
      name: '@MAXMIND/SurgicalPodWeaver'
      version: '0.0023'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@MAXMIND/PodSyntaxTests'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@MAXMIND/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: '0'
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: '0'
          phase: test
          script_finder:
            - ':ExecFiles'
          skips: []
      name: '@MAXMIND/Test::Compile'
      version: '2.051'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
      name: '@MAXMIND/Test::EOL'
      version: '0.16'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@MAXMIND/Test::NoTabs'
      version: '0.09'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@MAXMIND/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@MAXMIND/Test::Synopsis'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - .mailmap
            - Changes
            - cpanfile
            - CONTRIBUTING.md
            - LICENSE
            - Makefile.PL
            - README.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Check'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - .mailmap
            - Changes
            - cpanfile
            - CONTRIBUTING.md
            - LICENSE
            - Makefile.PL
            - README.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Commit'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v0.05
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Tag'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Push'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.030'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@MAXMIND/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.030'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.030'
x_authority: cpan:MAXMIND
